---

- hosts: localhost
  gather_facts: true
  become: yes
  tasks:
    - name: Run the specified shell command
      shell:
        cmd: |
              python3 ./lucky.py
      delegate_to: localhost
      connection: local
      register: result
    
    - name:
      ansible.builtin.command: whoami

    - name: Display the outcome
      debug:
        msg: '{{ result }}'
