---

- hosts: localhost
  gather_facts: true
  become_method: sudo
  become_user: root
  become: yes

  tasks:
    - name: Run the specified shell command
      shell:
        cmd: |
              python3 ./lucky.py
      delegate_to: localhost
      connection: local
      register: result
    
    - name:
      ansible.builtin.command: whoami
      register: whoisthis

    - name: Display the outcome
      debug:
        msg: '{{ result }}'

    - name: Display the whoami
      debug:
        msg: '{{ whoisthis }}'
        
    - name: test
      ansible.builtin.shell:
        cmd: ls -ltr
      register: result_yum
      
    - name: yum info zlib
      debug:
        msg: '{{ result_yum }}'
